In [1]:
import torch

# Создание тензора
t = torch.Tensor(3, 5, 2)
print(t)

# Либо так
t = torch.empty(3, 5, 2, dtype=torch.float32)
print(t.dtype)

tensor([[[1.5901e-30, 1.7124e-42],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])
torch.float32


In [2]:
# Создание тензора из списка
t = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(t)

# Индексация в pytorch выполняется так же, как в обычном python индексируются списки
print(t[0], t[-1], t[1:4:2])

t = torch.tensor([[1, 2, 3,], [4, 5, 6,], [7, 8, 9,]])
print(t)

# К размеру тензора можно обращаться с помощью методы size()
print(t.size())

# Или атрибутом shape
print(t.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor(1) tensor(10) tensor([2, 4])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.Size([3, 3])


In [3]:
# method_ такой метод изменяет текущий тензор и не создает нового
# metod такой метод не меняют текущий тензон, а формируют новый

t.fill_(1)
print(t)

t = torch.FloatTensor(2, 4).zero_()
print(t)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
# Создание пустого тензора
t_zeros = torch.zeros(2, 3)
print(t_zeros)

# Создание единичного тензора
t_ones = torch.ones(2, 3)
print(t_ones)

# Создание тензора с единичной диагональю
t_eye = torch.eye(2, 3)
print(t_eye)

# Создание тензора, заполненного определенными данными
t_full = torch.full((2, 4), 2)
print(t_full)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.]])
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])


In [5]:
# Один тензор можно представить в разных форматах
t = torch.arange(27)

# Представление в виде двумерного тензора
t1 = t.view(3, 9)
print(t1)

# Представление в виде трехмерного тензора
t2 = t.view(3, 3, 3)
print(t2)

# Изменяет формат тензора
t3 = t.resize_(2, 3)
print(t3, t)

# Вытягиевае тензор в вектор-строку
print(t.ravel())

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor([[0, 1, 2],
        [3, 4, 5]]) tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 1, 2, 3, 4, 5])


In [6]:
t = torch.unsqueeze(t, 1) # Добавляет новую ось
print(t)

t = torch.squeeze(t, 1) # Удаляет ось
print(t)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [7]:
# С помощью тензоров можно менять сразу группу значений
t[:2] = torch.IntTensor([-1, -2, -3])
print(t)

tensor([[-1, -2, -3],
        [-1, -2, -3]])


In [8]:
# Многомерная индексация происходит тем же образом, что и в numpy
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t[0, 0].item(), t[:, -1])
print(t[..., 1]) # Пропуск некоторых индексов 

1 tensor([3, 6])
tensor([2, 5])


In [9]:
import numpy as np
d_np = np.array([[1, 2, 3], [4, 5, 6]])
print(d_np)

# Из numpy array в pytorch tensor, сохранит тип данных
t = torch.from_numpy(d_np)
print(t)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
t = torch.tensor(d_np, dtype=torch.float32)
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
