## Тензоры в Pytorch

Тензоры PyTorch можно воспринимать, как многомерные матрицы. При этом все элементы одного тензора имеют единый тип данных.

### 1. Создание тензора

In [1]:
import torch

t = torch.Tensor(3, 5, 2)
print(t)

tensor([[[-6.5413e+32,  1.9660e-42],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]]])


Но в последних версиях рекомендуется использовать функцию empty:

In [2]:
t = torch.empty(3, 5, 2, dtype=torch.float32)
print(t.dtype)

torch.float32


В результате переменная t будет ссылаться на тензор размерностью (3, 5, 2), состоящий из случайных вещественных значений с типом данных float32.

Создание пустого тензора:

In [3]:
t_zeros = torch.zeros(2, 3)
print(t_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


Создание единичного тензора

In [4]:
t_ones = torch.ones(2, 3)
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


Создание тензора с единичной диагональю

In [5]:
t_eye = torch.eye(2, 3)
print(t_eye)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


Создание тензора, заполненного определенными данными

In [6]:
t_full = torch.full((2, 4), 2)
print(t_full)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])


```method_``` такой метод изменяет текущий тензор и не создает нового:

In [7]:
t.fill_(1)
print(t)

t = torch.FloatTensor(2, 4).zero_()
print(t)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2. Создание тензора из списка

In [8]:
t = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(t)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Индексация в pytorch выполняется так же, как в обычном python индексируются списки

In [9]:
print(t[0], t[-1], t[1:4:2])

tensor(1) tensor(10) tensor([2, 4])


In [10]:
t = torch.tensor([[1, 2, 3,], [4, 5, 6,], [7, 8, 9,]])
print(t)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


К размеру тензора можно обращаться с помощью методы size()

In [11]:
print(t.size())

torch.Size([3, 3])


Или атрибутом shape

In [12]:
print(t.shape)

torch.Size([3, 3])


### 3. Методы и представления тензоров

Один тензор можно представить в разных форматах

In [13]:
t = torch.arange(27)

Представление в виде двумерного тензора

In [14]:
t1 = t.view(3, 9)
print(t1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]])


Представление в виде трехмерного тензора

In [15]:
t2 = t.view(3, 3, 3)
print(t2)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


Изменяет формат тензора

In [16]:
t3 = t.resize_(2, 3)
print(t3, t)

tensor([[0, 1, 2],
        [3, 4, 5]]) tensor([[0, 1, 2],
        [3, 4, 5]])


Вытягиевае тензор в вектор-строку

In [17]:
print(t.ravel())

tensor([0, 1, 2, 3, 4, 5])


Добавляет новую ось

In [18]:
t = torch.unsqueeze(t, 1)
print(t)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])


Удаляет ось

In [19]:
t = torch.squeeze(t, 1)
print(t)

tensor([[0, 1, 2],
        [3, 4, 5]])


### 4. Индексация

С помощью тензоров можно менять сразу группу значений

In [20]:
t[:2] = torch.IntTensor([-1, -2, -3])
print(t)

tensor([[-1, -2, -3],
        [-1, -2, -3]])


Многомерная индексация происходит тем же образом, что и в numpy

In [21]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t[0, 0].item(), t[:, -1])
print(t[..., 1]) # Пропуск некоторых индексов 

1 tensor([3, 6])
tensor([2, 5])


Из numpy array в pytorch tensor, сохранит тип данных

In [22]:
import numpy as np
d_np = np.array([[1, 2, 3], [4, 5, 6]])
print(d_np)

t = torch.from_numpy(d_np)
print(t)    

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [23]:
t = torch.tensor(d_np, dtype=torch.float32)
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
