In [ ]:
import torch

a = torch.FloatTensor([1, 2, 3])
b = torch.IntTensor([3, 4, 5])

In [3]:
print(-a)

tensor([-1., -2., -3.])


In [4]:
print(a + 2)

tensor([3., 4., 5.])


In [5]:
print(2 + a)

tensor([3., 4., 5.])


In [6]:
print(a - 3)

tensor([-2., -1.,  0.])


In [7]:
print(a * 5)

tensor([ 5., 10., 15.])


In [8]:
print(a / 5)

tensor([0.2000, 0.4000, 0.6000])


In [9]:
print(a // 2)

tensor([0., 1., 1.])


In [10]:
print(a ** 3)

tensor([ 1.,  8., 27.])


In [11]:
print(a % 2)

tensor([1., 0., 1.])


In [14]:
print(a - b)

tensor([-2., -2., -2.])


In [15]:
print(b + a)

tensor([4., 6., 8.])


In [16]:
print(a * b)

tensor([ 3.,  8., 15.])


In [17]:
print(b / a)

tensor([3.0000, 2.0000, 1.6667])


In [18]:
print(b // a)

tensor([3., 2., 1.])


In [19]:
print(b ** a)

tensor([  3.,  16., 125.])


In [20]:
print(b % a)

tensor([0., 0., 2.])


In [22]:
# Поиск по тензору dim задает ось
print(a.mean(dim=0))
print(a.sum(dim=0))
print(a.max(dim=0).values)
print(a.min(dim=0).values)

tensor(2.)
tensor(6.)
tensor(3.)
tensor(1.)


In [23]:
# Тригонометрические функции и методы
a = torch.linspace(0, torch.pi, 10)

print(a.cos())

tensor([ 1.0000,  0.9397,  0.7660,  0.5000,  0.1736, -0.1736, -0.5000, -0.7660,
        -0.9397, -1.0000])


In [28]:
# Математическая статистика
x = torch.FloatTensor([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = torch.FloatTensor([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

In [29]:
# Медиана
print(torch.median(x))

tensor(8.)


In [30]:
# Дисперсия
print(x.var())

# СКО
print(x.std())

tensor(63.6556)
tensor(7.9784)


In [31]:
# Коэффициент корреляции Пирсона
XY = torch.vstack([x, y]) # Каждый тензор в отдельной строке
print(XY)
print(torch.corrcoef(XY))
print(torch.cov(XY))

tensor([[ 1.,  4.,  3.,  7., 10.,  8., 14., 21., 20., 23.],
        [ 4.,  1.,  6.,  9., 13., 11., 16., 19., 15., 22.]])
tensor([[1.0000, 0.9316],
        [0.9316, 1.0000]])
tensor([[63.6556, 49.8222],
        [49.8222, 44.9333]])
