## Математические операции с тензорами

### 1. Базовые математические операции

In [1]:
import torch

a = torch.FloatTensor([1, 2, 3])
print(a)

tensor([1., 2., 3.])


In [2]:
b = torch.IntTensor([3, 4, 5])
print(b)

tensor([3, 4, 5], dtype=torch.int32)


Изменение знака:

In [3]:
print(-a)

tensor([-1., -2., -3.])


Прибавить константу:

In [4]:
print(a + 2)

tensor([3., 4., 5.])


Переместительное свойство сложения:

In [5]:
print(2 + a)

tensor([3., 4., 5.])


Вычитание константы:

In [6]:
print(a - 3)

tensor([-2., -1.,  0.])


Умножение на константу:

In [7]:
print(a * 5)

tensor([ 5., 10., 15.])


Деление на константу:

In [8]:
print(a / 5)

tensor([0.2000, 0.4000, 0.6000])


Целочисленное деление на константу:

In [9]:
print(a // 2)

tensor([0., 1., 1.])


Возведение в степень:

In [10]:
print(a ** 3)

tensor([ 1.,  8., 27.])


Остаток от деления:

In [11]:
print(a % 2)

tensor([1., 0., 1.])


Вычитание тензоров друг из друга:

In [12]:
print(a - b)

tensor([-2., -2., -2.])


Сложение тензоров:

In [13]:
print(b + a)

tensor([4., 6., 8.])


Складывать тензоры разной длины **нельзя**. Но, если у тензоров совпадает длина строк, можно выполнить:

In [14]:
c = torch.arange(1, 7).view(2, 3)
print(a + b)

tensor([4., 6., 8.])


Умножение тензоров:

In [15]:
print(a * b)

tensor([ 3.,  8., 15.])


Деление тензоров:

In [16]:
print(b / a)

tensor([3.0000, 2.0000, 1.6667])


Целочисленное деление тензоров:

In [17]:
print(b // a)

tensor([3., 2., 1.])


Возведение тензоров в степень:

In [18]:
print(b ** a)

tensor([  3.,  16., 125.])


Деление тензоров с остатком:

In [19]:
print(b % a)

tensor([0., 0., 2.])


Поиск по тензору, ``dim`` задает ось:

In [20]:
print(a.mean(dim=0))
print(a.sum(dim=0))
print(a.max(dim=0).values)
print(a.min(dim=0).values)

tensor(2.)
tensor(6.)
tensor(3.)
tensor(1.)


При выполнении арифметических операций тип данных автоматически приводится к более общему:

In [21]:
a = torch.IntTensor([1, 2, 6, 8])
a += 5

b = torch.ones(4)
b *= a

# Выбрасывает ошибку
a += b

RuntimeError: result type Float can't be cast to the desired output type Int

Результат сложения вещественного числа с целочисленным, итоговое значение представляет собой вещественное число. Но тип данных массива a — целочисленный и он не может сохранять вещественные числа. Отсюда и возникает эта ошибка. 

### 2. Тригонометрические и статистические функции и методы

In [22]:
a = torch.linspace(0, torch.pi, 10)

print(a.cos())

tensor([ 1.0000,  0.9397,  0.7660,  0.5000,  0.1736, -0.1736, -0.5000, -0.7660,
        -0.9397, -1.0000])


Очень часто на практике требуется вычислять сумму значений элементов тензоров, их среднее значение, а также находить минимальные и максимальные значения. Для этих целей в PyTorch существуют встроенные методы тензоров, выполняющие эти действия:

In [23]:
x = torch.FloatTensor([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = torch.FloatTensor([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

Сумма:

In [24]:
print(x.sum())

tensor(111.)


По конкретной оси для многомерных массивов:

In [26]:
z = x.view(5, 2)

print(z.sum(dim=0))
print(z.sum(dim=1))

tensor([48., 63.])
tensor([ 5., 10., 18., 35., 43.])


Среднее:

In [27]:
x.mean()

tensor(11.1000)

Максимум значение:

In [28]:
x.max()

tensor(23.)

Если вычислить максимальное значение по оси, получим ``torch.return_types.max()``:

In [34]:
print(z.max(dim=1))

torch.return_types.max(
values=tensor([ 4.,  7., 10., 21., 23.]),
indices=tensor([1, 1, 0, 1, 1]))


То есть, здесь возвращается последовательность из двух элементов. Чтобы выделить только максимальные значения нужно дополнительно указать атрибут values:

In [35]:
print(z.max(dim=1).values)

tensor([ 4.,  7., 10., 21., 23.])


Минимум значения:

In [36]:
x.min()

tensor(1.)

Медиана:

In [37]:
print(torch.median(x))

tensor(8.)


Дисперсия:

In [38]:
print(x.var())

tensor(63.6556)


СКО:

In [39]:
print(x.std())

tensor(7.9784)


Коэффициент корреляции Пирсона:

In [40]:
# Каждый тензор в отдельной строке
XY = torch.vstack([x, y])

print(XY)
print(torch.corrcoef(XY))
print(torch.cov(XY))

tensor([[ 1.,  4.,  3.,  7., 10.,  8., 14., 21., 20., 23.],
        [ 4.,  1.,  6.,  9., 13., 11., 16., 19., 15., 22.]])
tensor([[1.0000, 0.9316],
        [0.9316, 1.0000]])
tensor([[63.6556, 49.8222],
        [49.8222, 44.9333]])
